INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("Southern Lucy Burger", "Burger21", "Angus beef burger stuffed with cheese, topped with crispy onion strings and bacon aïoli, placed on bed of house-made tomato jam on a toasted brioche bun.", false);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("The WolfPack", "Tribeca Tavern", "Two 5oz Patties, Ashe County Pepper Jack, Peppered Bacon, BBQ Sauce, Fried Onion Straws, LTO, Brioche Bun.", false);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("Blanco Burger", "Zinburger", "Pepper Jack Cheese, Pico De Gallo, Guacamole, Lettuce & Chipotle Mayo", false);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("Bad Ass Burger", "Big Daddy's Burger Bar", "A massive 10 oz. beef patty with Housemade American cheese, buttermilk-fried bacon, horseradish mayo, lettuce, tomato & pickles.", false);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("Smokehouse", "Town Hall Burger & Beer", "Our signature Angus patty topped with pulled pork, pepper jack cheese, onion straws & housemade apple-bacon BBQ sauce.", false);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("California Burger", "Big Daddy's Burger Bar", "Certified Angus Beef patty, applewood smoked bacon, guacamole, lettuce, pico de gallo & chipotle mayo on brioche", false);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("El Diablo", "Zinburger", "Fire Roasted Jalapeños, Pepper Jack Cheese, Braised Onions, Lettuce & Chipotle Mayo", true);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("Buffalo Chicken Burger", "Burger21", "Frank’s RedHot sauce, bleu cheese crumbles, ranch dressing, crispy buffalo chicken burger, lettuce, tomato, brioche bun", true);
INSERT INTO burgers (burger_name, rest_name, description, devoured) VALUES ("The Imp", "Tribeca Tavern", "Blackened, Ashe County Pepper Jack, Caramelized Onions, Green Peppers, Guacamole, Chimichuri Aioli, Fresh Jalapeño, LTO, Pretzel Bun", true);
